services:
  bifrost:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: abc1234
        APP_VERSION: 1.2.3
    container_name: bifrost
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./config:/config